import type { LangCode } from "./types";

export interface Currency {
  code: string;
  symbol: string;
  name: Record<LangCode, string>;
  nations: string[];
}

export const CURRENCIES: Currency[] = [
  {
    code: "RUB",
    symbol: "₽",
    nations: ["ru"],
    name: {
      ru: "Российский рубль",
      en: "Russian ruble",
      uk: "Російський рубль",
      kk: "Ресей рублі",
      es: "Rublo ruso",
      fr: "Rouble russe",
      de: "Russischer Rubel",
      pt: "Rublo russo",
      tr: "Rus rublesi",
      az: "Rusiya rublu",
      pl: "Rubel rosyjski",
      it: "Rublo russo",
    },
  },
  {
    code: "USD",
    symbol: "$",
    nations: ["en"],
    name: {
      ru: "Доллар США",
      en: "US dollar",
      uk: "Долар США",
      kk: "АҚШ доллары",
      es: "Dólar estadounidense",
      fr: "Dollar américain",
      de: "US-Dollar",
      pt: "Dólar americano",
      tr: "ABD doları",
      az: "ABŞ dolları",
      pl: "Dolar amerykański",
      it: "Dollaro USA",
    },
  },
  {
    code: "EUR",
    symbol: "€",
    nations: ["de", "fr", "es", "it", "pt"],
    name: {
      ru: "Евро",
      en: "Euro",
      uk: "Євро",
      kk: "Еуро",
      es: "Euro",
      fr: "Euro",
      de: "Euro",
      pt: "Euro",
      tr: "Euro",
      az: "Avro",
      pl: "Euro",
      it: "Euro",
    },
  },
  {
    code: "UAH",
    symbol: "₴",
    nations: ["uk"],
    name: {
      ru: "Гривна",
      en: "Ukrainian hryvnia",
      uk: "Гривня",
      kk: "Гривна",
      es: "Grivna ucraniana",
      fr: "Hryvnia ukrainienne",
      de: "Ukrainische Hrywnja",
      pt: "Hryvnia ucraniana",
      tr: "Ukrayna grivnası",
      az: "Ukrayna qrivnası",
      pl: "Hrywna",
      it: "Grivnia ucraina",
    },
  },
  {
    code: "KZT",
    symbol: "₸",
    nations: ["kk"],
    name: {
      ru: "Тенге",
      en: "Kazakh tenge",
      uk: "Тенге",
      kk: "Теңге",
      es: "Tenge kazajo",
      fr: "Tenge kazakh",
      de: "Kasachischer Tenge",
      pt: "Tenge cazaque",
      tr: "Kazak tengesi",
      az: "Qazax təngəsi",
      pl: "Tenge",
      it: "Tenge kazako",
    },
  },
  {
    code: "BYN",
    symbol: "Br",
    nations: [],
    name: {
      ru: "Белорусский рубль",
      en: "Belarusian ruble",
      uk: "Білоруський рубль",
      kk: "Беларусь рублі",
      es: "Rublo bielorruso",
      fr: "Rouble biélorusse",
      de: "Belarussischer Rubel",
      pt: "Rublo bielorrusso",
      tr: "Belarus rublesi",
      az: "Belarus rublu",
      pl: "Rubel białoruski",
      it: "Rublo bielorusso",
    },
  },
  {
    code: "PLN",
    symbol: "zł",
    nations: ["pl"],
    name: {
      ru: "Злотый",
      en: "Polish zloty",
      uk: "Злотий",
      kk: "Злотый",
      es: "Zloty polaco",
      fr: "Zloty polonais",
      de: "Polnischer Zloty",
      pt: "Zloty polonês",
      tr: "Polonya zlotisi",
      az: "Polşa zlotisi",
      pl: "Polski złoty",
      it: "Zloty polacco",
    },
  },
  {
    code: "CZK",
    symbol: "Kč",
    nations: [],
    name: {
      ru: "Чешская крона",
      en: "Czech koruna",
      uk: "Чеська крона",
      kk: "Чех кронасы",
      es: "Corona checa",
      fr: "Couronne tchèque",
      de: "Tschechische Krone",
      pt: "Coroa checa",
      tr: "Çek korunası",
      az: "Çex kronu",
      pl: "Korona czeska",
      it: "Corona ceca",
    },
  },
  {
    code: "GBP",
    symbol: "£",
    nations: ["en"],
    name: {
      ru: "Фунт стерлингов",
      en: "British pound",
      uk: "Фунт стерлінгів",
      kk: "Фунт стерлинг",
      es: "Libra esterlina",
      fr: "Livre sterling",
      de: "Pfund Sterling",
      pt: "Libra esterlina",
      tr: "İngiliz sterlini",
      az: "Britaniya funtu",
      pl: "Funt szterling",
      it: "Sterlina britannica",
    },
  },
  {
    code: "TRY",
    symbol: "₺",
    nations: ["tr"],
    name: {
      ru: "Турецкая лира",
      en: "Turkish lira",
      uk: "Турецька ліра",
      kk: "Түрік лирасы",
      es: "Lira turca",
      fr: "Livre turque",
      de: "Türkische Lira",
      pt: "Lira turca",
      tr: "Türk lirası",
      az: "Türk lirəsi",
      pl: "Lira turecka",
      it: "Lira turca",
    },
  },
  {
    code: "AZN",
    symbol: "₼",
    nations: ["az"],
    name: {
      ru: "Азербайджанский манат",
      en: "Azerbaijani manat",
      uk: "Азербайджанський манат",
      kk: "Әзірбайжан манаты",
      es: "Manat azerí",
      fr: "Manat azerbaïdjanais",
      de: "Aserbaidschan-Manat",
      pt: "Manat azeri",
      tr: "Azerbaycan manatı",
      az: "Azərbaycan manatı",
      pl: "Manat azerbejdżański",
      it: "Manat azero",
    },
  },
  {
    code: "BRL",
    symbol: "R$",
    nations: ["pt"],
    name: {
      ru: "Бразильский реал",
      en: "Brazilian real",
      uk: "Бразильський реал",
      kk: "Бразилия реалы",
      es: "Real brasileño",
      fr: "Réal brésilien",
      de: "Brasilianischer Real",
      pt: "Real brasileiro",
      tr: "Brezilya reali",
      az: "Braziliya realı",
      pl: "Real brazylijski",
      it: "Real brasiliano",
    },
  },
  {
    code: "CNY",
    symbol: "¥",
    nations: [],
    name: {
      ru: "Китайский юань",
      en: "Chinese yuan",
      uk: "Китайський юань",
      kk: "Қытай юані",
      es: "Yuan chino",
      fr: "Yuan chinois",
      de: "Chinesischer Yuan",
      pt: "Yuan chinês",
      tr: "Çin yuanı",
      az: "Çin yuanı",
      pl: "Yuan chiński",
      it: "Yuan cinese",
    },
  },
  {
    code: "JPY",
    symbol: "¥",
    nations: [],
    name: {
      ru: "Японская иена",
      en: "Japanese yen",
      uk: "Японська єна",
      kk: "Жапон иенасы",
      es: "Yen japonés",
      fr: "Yen japonais",
      de: "Japanischer Yen",
      pt: "Iene japonês",
      tr: "Japon yeni",
      az: "Yapon yeni",
      pl: "Jen japoński",
      it: "Yen giapponese",
    },
  },
  {
    code: "KRW",
    symbol: "₩",
    nations: [],
    name: {
      ru: "Южнокорейская вона",
      en: "South Korean won",
      uk: "Південнокорейська вона",
      kk: "Оңтүстік Корея воны",
      es: "Won surcoreano",
      fr: "Won sud-coréen",
      de: "Südkoreanischer Won",
      pt: "Won sul-coreano",
      tr: "Güney Kore wonu",
      az: "Cənubi Koreya vonu",
      pl: "Won południowokoreański",
      it: "Won sudcoreano",
    },
  },
  {
    code: "INR",
    symbol: "₹",
    nations: [],
    name: {
      ru: "Индийская рупия",
      en: "Indian rupee",
      uk: "Індійська рупія",
      kk: "Үнді рупиясы",
      es: "Rupia india",
      fr: "Roupie indienne",
      de: "Indische Rupie",
      pt: "Rupia indiana",
      tr: "Hindistan rupisi",
      az: "Hindistan rupisi",
      pl: "Rupia indyjska",
      it: "Rupia indiana",
    },
  },
  {
    code: "CHF",
    symbol: "Fr",
    nations: ["de", "fr", "it"],
    name: {
      ru: "Швейцарский франк",
      en: "Swiss franc",
      uk: "Швейцарський франк",
      kk: "Швейцария франкі",
      es: "Franco suizo",
      fr: "Franc suisse",
      de: "Schweizer Franken",
      pt: "Franco suíço",
      tr: "İsviçre frangı",
      az: "İsveçrə frankı",
      pl: "Frank szwajcarski",
      it: "Franco svizzero",
    },
  },
  {
    code: "SEK",
    symbol: "kr",
    nations: [],
    name: {
      ru: "Шведская крона",
      en: "Swedish krona",
      uk: "Шведська крона",
      kk: "Швед кронасы",
      es: "Corona sueca",
      fr: "Couronne suédoise",
      de: "Schwedische Krone",
      pt: "Coroa sueca",
      tr: "İsveç kronu",
      az: "İsveç kronu",
      pl: "Korona szwedzka",
      it: "Corona svedese",
    },
  },
  {
    code: "NOK",
    symbol: "kr",
    nations: [],
    name: {
      ru: "Норвежская крона",
      en: "Norwegian krone",
      uk: "Норвезька крона",
      kk: "Норвег кронасы",
      es: "Corona noruega",
      fr: "Couronne norvégienne",
      de: "Norwegische Krone",
      pt: "Coroa norueguesa",
      tr: "Norveç kronu",
      az: "Norveç kronu",
      pl: "Korona norweska",
      it: "Corona norvegese",
    },
  },
  {
    code: "CAD",
    symbol: "C$",
    nations: ["en", "fr"],
    name: {
      ru: "Канадский доллар",
      en: "Canadian dollar",
      uk: "Канадський долар",
      kk: "Канада доллары",
      es: "Dólar canadiense",
      fr: "Dollar canadien",
      de: "Kanadischer Dollar",
      pt: "Dólar canadense",
      tr: "Kanada doları",
      az: "Kanada dolları",
      pl: "Dolar kanadyjski",
      it: "Dollaro canadese",
    },
  },
  {
    code: "AUD",
    symbol: "A$",
    nations: ["en"],
    name: {
      ru: "Австралийский доллар",
      en: "Australian dollar",
      uk: "Австралійський долар",
      kk: "Аустралия доллары",
      es: "Dólar australiano",
      fr: "Dollar australien",
      de: "Australischer Dollar",
      pt: "Dólar australiano",
      tr: "Avustralya doları",
      az: "Avstraliya dolları",
      pl: "Dolar australijski",
      it: "Dollaro australiano",
    },
  },
  {
    code: "MXN",
    symbol: "MX$",
    nations: ["es"],
    name: {
      ru: "Мексиканское песо",
      en: "Mexican peso",
      uk: "Мексиканське песо",
      kk: "Мексика песосы",
      es: "Peso mexicano",
      fr: "Peso mexicain",
      de: "Mexikanischer Peso",
      pt: "Peso mexicano",
      tr: "Meksika pesosu",
      az: "Meksika pesosu",
      pl: "Peso meksykańskie",
      it: "Peso messicano",
    },
  },
  {
    code: "GEL",
    symbol: "₾",
    nations: [],
    name: {
      ru: "Грузинский лари",
      en: "Georgian lari",
      uk: "Грузинський ларі",
      kk: "Грузин лариі",
      es: "Lari georgiano",
      fr: "Lari géorgien",
      de: "Georgischer Lari",
      pt: "Lari georgiano",
      tr: "Gürcistan larisi",
      az: "Gürcü larisi",
      pl: "Lari gruzińskie",
      it: "Lari georgiano",
    },
  },
  {
    code: "AMD",
    symbol: "֏",
    nations: [],
    name: {
      ru: "Армянский драм",
      en: "Armenian dram",
      uk: "Вірменський драм",
      kk: "Армян драмы",
      es: "Dram armenio",
      fr: "Dram arménien",
      de: "Armenischer Dram",
      pt: "Dram armênio",
      tr: "Ermeni dramı",
      az: "Erməni dramı",
      pl: "Dram ormiański",
      it: "Dram armeno",
    },
  },
  {
    code: "UZS",
    symbol: "so'm",
    nations: [],
    name: {
      ru: "Узбекский сум",
      en: "Uzbek som",
      uk: "Узбецький сум",
      kk: "Өзбек сомы",
      es: "Som uzbeko",
      fr: "Sum ouzbek",
      de: "Usbekischer Sum",
      pt: "Som uzbeque",
      tr: "Özbek somu",
      az: "Özbək somu",
      pl: "Sum uzbecki",
      it: "Som uzbeco",
    },
  },
  {
    code: "AED",
    symbol: "د.إ",
    nations: [],
    name: {
      ru: "Дирхам ОАЭ",
      en: "UAE dirham",
      uk: "Дирхам ОАЕ",
      kk: "БАӘ дирхамы",
      es: "Dírham de los EAU",
      fr: "Dirham des EAU",
      de: "VAE-Dirham",
      pt: "Dirham dos EAU",
      tr: "BAE dirhemi",
      az: "BƏƏ dirhəmi",
      pl: "Dirham ZEA",
      it: "Dirham degli EAU",
    },
  },
];

export const CURRENCY_BY_CODE = Object.fromEntries(
  CURRENCIES.map((c) => [c.code, c]),
) as Record<string, Currency>;

export const DEFAULT_CURRENCY_BY_LANG: Record<LangCode, string> = {
  ru: "RUB",
  en: "USD",
  uk: "UAH",
  kk: "KZT",
  es: "EUR",
  fr: "EUR",
  de: "EUR",
  pt: "BRL",
  tr: "TRY",
  az: "AZN",
  pl: "PLN",
  it: "EUR",
};

export function currencySymbol(code: string): string {
  return CURRENCY_BY_CODE[code]?.symbol ?? code;
}
